[supabase]
url = "https://fcyutudqmkhrywffsjky.supabase.co"
anon_key = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjeXV0dWRxbWtocnl3ZmZzamt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0MjQ3OTAsImV4cCI6MjA1ODAwMDc5MH0.IucZQwgH1CFYFCgb9E3-TV7I-NOnPq9-3lmrWc4ZE7I"

[openai]
api_key = "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"
org_id = "org-ayjb7S9GrSniHDb8UqmYapv0"

[analytics]
enabled = true
tracking_id = ""  # Add your tracking ID here

[cache]
ttl = 3600  # Cache TTL in seconds
max_entries = 1000 

[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "k8Qw1nQ2v1J3l4K5m6N7o8P9q0R1s2T3u4V5w6X7y8Z9a0B1"
client_id = "86553633243-38nlupd79ddlf7a2q4nc80uda5s8nlbc.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"
